### ISSUE TITLE
Implement a favicon

### ISSUE THREAD

**Issue by relandboyle** [Linkta-org/core#104]
**Related User Story**

**Related Tickets**

**Acceptance Criteria**

The favicon is the image used to represent the Linkta application in browser tabs, etc.
Follow best practices to provide a clearly identifiable icon in multiple resolutions.

**Subtasks**
<!-- If necessary, break down the ticket into smaller, actionable subtasks. Create issues accordingly.>

**Comment by colinvandergraaf** [comment]
![Screenshot 2024-05-31 at 10 48 41 AM](https://github.com/Linkta-org/core/assets/60681566/81f4ef47-0962-4e6e-ac98-b15eb4f81479)
Is the blue icon what we're going for in safari?  Why is this different than other browsers?
