### ISSUE TITLE
Provide UI for users to delete input

### ISSUE THREAD

**Issue by ChTiSh** [Linkta-org/core#149]
### Acceptance criteria
- Implement the confirmation dialog exactly as shown in the [mockup](https://www.figma.com/design/9QKsvDQ9jivgA9XfS0oqPd/Design-System---Linkta?node-id=2453-7935&t=Rwnz7IlUEgIWybky-0)
  - Position the component in the location specified in the mockup
  - Use the correct colors, fonts, and dimensions as detailed in the design specs
  - Implement all interactive states (e.g., hover, active, disabled) as per the mockup
  - Ensure the component's responsiveness matches the mockup across different screen sizes
- Confirmation dialog is shown before deleting a LinktaFlow.
- Ensure accessibility.
- Error handling with SnackBarNotification is in place
- React Query setup in #253 is integrated with the component

**Comment by kinskiwu** [comment]
#265 in review. Use this ticket to create the UI and #253 to implement React Query.

**Comment by kinskiwu** [comment]
Axios has been set up in #265. Please use this issue for the UI (including styling).
