### ISSUE TITLE
Implement Backend for Storing LinktaFlow object into DB

### ISSUE THREAD

**Issue by zhiyi15** [Linkta-org/core#205]
**Related Epic**
#120 

**Acceptance Criteria**
- Refactor LinktaFlowController based on latest API design doc
- Integrate LinktaFlowController into genAIController
- Remove unused LLM related files

**Subtasks**
<!-- If necessary, break down the ticket into smaller, actionable subtasks. Create issues accordingly.>

**Comment by relandboyle** [comment]
Duplicate of #233
