### ISSUE TITLE
Refactor: Override Default MUI Selected Menu Item Behavior in OptionsMenu to Match Mockup Design

### ISSUE THREAD

**Issue by kinskiwu** [Linkta-org/core#207]
**Description**
The default MUI behavior for selected menu items in OptionsMenu persists the highlight of the first child of the selected menu item. This behavior is inconsistent with the mockup design, which requires a different highlight behavior.

**Acceptance Criteria**
- Ensure that the highlight behavior matches the mockup design.
- Verify that the first child of the selected menu item does not persist the highlight.

**Comment by relandboyle** [comment]
@kinskiwu Would you agree that this issue can be closed?

**Comment by kinskiwu** [comment]
Closing this ticket as new ticket #416 created
