### ISSUE TITLE
Create contribution guidelines

### ISSUE THREAD

**Issue by ejwoods** [Linkta-org/core#232]
## Description

Open Source repositories often have guidelines for how contributors can work on the project. We should create a CONTRIBUTING.md file that outlines this process for any potential or current Linkta contributors. See more here: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

## More detail

The specific impetus for this issue is that @relandboyle and I tracked down an issue I was having post-app-split where my ESLint extension was false-flagging the error: `Parsing error: Cannot read file '/absolute/path/to/Core/tsconfig.json'` at the first import statement in basically every file. Essentially, the problem was that although we had correctly set up our separate ESLint configs in the server and client directories - which allowed ESLint to run correctly without hitting this error - the extension was unaware of this and falsely alerting me that this error would occur when I ran ESLint. 

The solution is to configure the `eslint.workingDirectories` setting in VS Code settings. I set this in my workspace settings for the Core repo by adding the following line to my .vscode/settings.json at the root of the repository:
```
"eslint.workingDirectories": [ "./client", "./server" ]
```

This informs the extension of our app’s file structure so that it can properly anticipate the behavior of the ESLint module itself.

While the experience of figuring this out was extremely enlightening, it took us a while to reach this conclusion and I think it warrants a mention in our contribution guidelines. 

## Acceptance Criteria

- CONTRIBUTING.md file is created that describes how users can contribute to this repo

## Subtasks

 - create basic CONTRIBUTING.md that outlines bare basics of contributing to Linkta
 - add section for configuring the ESLint extension for VS Code

**Comment by relandboyle** [comment]
Strongly agree. Thank you for writing this up.

**Comment by ejwoods** [comment]
Potential for an added setting here - might need to add `changeProcessCWD` to options:

```
  "eslint.workingDirectories": [
    { "directory": "./client", "changeProcessCWD": true },
    { "directory": "./server", "changeProcessCWD": true }
  ],
```

Related issue here: https://github.com/microsoft/vscode-eslint/issues/656

**Comment by ejwoods** [comment]
Looks like since version 2.0.4, 'the extension now changes the working directory by default.' So explicitly setting `changeProcessCWD` is probably no longer necessary. [Release notes here.](https://github.com/Microsoft/vscode-eslint?tab=readme-ov-file#version-204)
