### ISSUE TITLE
Integrate Existing SnackBarNotification into Frontend Components

### ISSUE THREAD

**Issue by kinskiwu** [Linkta-org/core#247]
**Related to**
#355 

**Description**
Incorporate the previously implemented SnackBarNotification component across various frontend components to provide consistent, non-intrusive user feedback for different actions and events.

**Acceptance Criteria**
- Identify frontend components where SnackBarNotification should be integrated
- Implement SnackBarNotification calls in these components for appropriate user actions
- Ensure correct usage of notification types for each integration
- Verify that notifications don't interfere with existing UI elements

**Comment by relandboyle** [comment]
I'm marking this issue as "XL" because I suspect that various views and components will have unique behaviors and needs, and some may be more complex than others.
