### ISSUE TITLE
Verify/Finish Github Auth Functionality in Client App 

### ISSUE THREAD

**Issue by colinvandergraaf** [Linkta-org/core#281]
**Related User Story**

Verify and implement the remaining functionality for using Github Auth to login to Linkta. 

Make sure the useSignInWIthGithub hook does what it says.  

NOTE: This ticket is blocked until we have the URL for a hosted client application.  

**Related Tickets**

Related Epic: https://github.com/Linkta-org/core/issues/185
**Acceptance Criteria**

User shoudl be able to click the Github auth buttons on SignIn Page and SignUp Page and login to Linkta

**Subtasks**
<!-- If necessary, break down the ticket into smaller, actionable subtasks. Create issues accordingly.>

**Comment by relandboyle** [comment]
@colinvandergraaf Can we mark this one as completed? There is a public URL now, and auth with GitHub is working.

**Comment by colinvandergraaf** [comment]
👍 Thans to whoever completed this one!
