### ISSUE TITLE
Unit Test - Client - Auth Pages

### ISSUE THREAD

**Issue by relandboyle** [Linkta-org/core#339]
**Related User Story**

**Related Tickets**

#337 

**Acceptance Criteria**

**Subtasks**
<!-- If necessary, break down the ticket into smaller, actionable subtasks. Create issues accordingly.>

**Comment by ejwoods** [comment]
# Acceptance criteria:

### Unit tests for features/auth-pages:

1. ForgotPasswordPage
2. PasswordUpdatePage
3. <s>SignIn Page</s> 
4. SignUpPage
5. UnauthorizedLayout

### Tests should verify:
- render of key elements by accessible labels
- interactivity

### Future tickets should add tests to verify:
- additional ARIA attributes
- validation
- error handling
- stage management
- data fetching
- css & responsiveness - _pages are not currently fully responsive at smaller screen sizes_
