### ISSUE TITLE
Unit Test - Server - genAiController

### ISSUE THREAD

**Issue by relandboyle** [Linkta-org/core#343]
**Related User Story**

**Related Tickets**

#337 

**Acceptance Criteria**

**Subtasks**
<!-- If necessary, break down the ticket into smaller, actionable subtasks. Create issues accordingly.>

**Comment by kinskiwu** [comment]
CLosing this ticket because getnAIController is not used in our app and probably will remove it in the future. We are only using aiServices atm.
