### ISSUE TITLE
LinktaFlow orientation is displayed in "portrait" orientation to allow for easier full screen viewing

### ISSUE THREAD

**Issue by LucieSeidler** [Linkta-org/core#360]
**Related User Story**

**Related Tickets**

Ensure LinktaFlow object is displayed properly #352

**Acceptance Criteria**

LinktaFlow created from LLM response using Dagre is generally in "portrait" orientation

**Subtasks**
<!-- If necessary, break down the ticket into smaller, actionable subtasks. Create issues accordingly.>

**Comment by relandboyle** [comment]
We may decide to close this task.

Research shows that nothing in a prompt or tool will cause the LLM to consider token count when constructing the response. However, manipulating the prompt to limit the total number of nodes and the number of child nodes at each level has made a significant improvement. 

Before:
![image](https://github.com/user-attachments/assets/5c6bb965-fab1-46b1-95dd-6f35d21007b4)

After:
![image](https://github.com/user-attachments/assets/e310defd-86b9-446e-a390-aacce2b7ac7c)
