### ISSUE TITLE
.prettierrc.json is configured to use double quotes over single quotes.

### ISSUE THREAD

**Issue by dcpavel** [Linkta-org/core#38]
**Describe the bug**
We have discussed and determined to use single quotes on this project. However, the .prettierrc.json file contains "singleQuote": false.

**To Reproduce**
1. Open the project
2. Navigate to .prettierrc.json
3. See line 15

**Expected behavior**
We expect this value to be true.
While investigating the issue some more, it appears that we don't need to use overrides in .eslintrc.json for the prettier configuration. This will leave us with a single source of configuration.

Please see [this Medium article](https://medium.com/@fabianterh/an-opinionated-guide-to-setting-up-prettier-with-eslint-51809b1b3043)

**Screenshots**
<img width="248" alt="image" src="https://github.com/Linkta-org/core/assets/1166090/12f4bb3d-dda0-427c-a29d-3afc598cdd60">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: VSCode
 - Version: 1.87.2

**Additional context**

**Comment by ChTiSh** [comment]
I will work on this issue.

**Comment by ChTiSh** [comment]
PR is in for this: https://github.com/Linkta-org/core/pull/40
