### ISSUE TITLE
Remove temporary Linkta logo from "unauthorized" static layout

### ISSUE THREAD

**Issue by relandboyle** [Linkta-org/core#383]
**Related User Story**
Colin recently updated the Linkta logo image to have a proper transparent background.
Display the same logo on both authorized and unauthorized static layouts.
Display the logo with padding.
Make the logo link to home-page route.

**Related Tickets**

**Acceptance Criteria**

**Subtasks**
<!-- If necessary, break down the ticket into smaller, actionable subtasks. Create issues accordingly.>

**Comment by kinskiwu** [comment]
@relandboyle is this ticket still relevant after your most recent changes to the layout?
