### ISSUE TITLE
Update mockups for UserInput submission UI on Figma

### ISSUE THREAD

**Issue by kinskiwu** [Linkta-org/core#81]
## Acceptance criteria

**Comment by ChTiSh** [comment]
Draft ready for review: 
https://www.figma.com/design/9QKsvDQ9jivgA9XfS0oqPd/Design-System---Linkta?node-id=2154%3A8640&t=sXtGQ9g9TRFotY1T-1

**Comment by relandboyle** [comment]
I have reviewed and I think it looks great. Approved!
