### ISSUE TITLE
Config Overhaul - esLint, Prettier, TypeScript, GH Actions

### ISSUE THREAD

**Issue by relandboyle** [Linkta-org/core#95]
**Describe the bug**
There's a problem with the Linkta Core repository and GitHub Actions. My understanding is that it's configured to apply formatting and typing rules to Git commits before a Pull Request can be created. This should be okay if everyone has the same formatting and typing rules defined in their local config files, right? But something isn't right, because it isn't working.

On a related note, some of us are thinking there may be a need for a review / possible reset of our formatting and typing rules. There's some stuff in there that feels pretty unnatural to many of us.

**To Reproduce**
Attempt to push code and open a pull request

**Expected behavior**
Successfully open a PR

**Actual Behavior**
PR is blocked by GitHub Actions

**Comment by ChTiSh** [comment]
Closing this as PR merged: https://github.com/Linkta-org/core/pull/114
